name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
      name: Check Out Source
    - name: Set up .NET Core SDK for Tools
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: Set Up .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install Tools
      run: |
        dotnet tool restore
    - name: Generate Version Number
      run: >
        dotnet tool run
        dotnet-gitversion
        --
        -output json
        -updateAssemblyInfo
    - name: Run Build
      run: dotnet build -c Release
    - name: Run Tests
      run: >
        dotnet
        test
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=OpenCover
        /p:Exclude="+[Oxide*]*%2c-[Oxide.Tests]*"
    - name: Upload Coverage
      run: >
        dotnet tool run
        codecov
        --
        -f "src/Oxide.Tests/coverage.opencover.xml"
        -t ${{ secrets.CODECOV_TOKEN }}