name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check Out Source
    - name: Set up .NET Core SDK for Tools
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: Set Up .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install Tools
      run: |
        dotnet tool install -g gitversion.tool
        dotnet tool install -g sleet
        dotnet tool install -g codecov.tool
    - name: Generate Version Number
      run: |
        ~/.dotnet/tools/dotnet-gitversion -updateAssemblyInfo
        echo "::set-env name=PackageVersion::$(~/.dotnet/tools/dotnet-gitversion -showvariable NugetVersion)"
    - name: Run Build
      run: dotnet build -c Release
    - name: Run Tests
      run: >
        dotnet
        test
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=OpenCover
        /p:Exclude="+[Oxide*]*%2c-[Oxide.Tests]*"
    - name: Upload Coverage
      run: |
        export DOTNET_ROOT=/opt/hostedtoolcache/dncs/2.2.204/x64
        ~/.dotnet/tools/codecov -f "src/Oxide.Tests/coverage.opencover.xml" -t ${{ secrets.CODECOV_TOKEN }}
    - name: Pack NuGet
      run: >
        dotnet
        msbuild
        /t:Restore,Pack
        /p:IncludeSymbols=true
        /p:SymbolPackageFormat=snupkg
        /p:Configuration=Release
        /p:PackageOutputPath=artifacts
        /p:Version=$PackageVersion
        /v:minimal
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Packages
        path: artifacts