name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check Out Source
    - name: Prepare repository
      run: |
        git checkout master
        git checkout "${GITHUB_REF:11}"
    - name: Set Up .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install Tools
      run: |
        dotnet tool install -g --version 1.9.0 codecov.tool
        dotnet tool install -g --version 5.1.3 gitversion.tool
        dotnet tool install -g --version 3.0.20 sleet
    - name: Generate Version Number
      run: |
        ~/.dotnet/tools/dotnet-gitversion /updateAssemblyInfo /output json | tee -a version.json
        echo "::set-env name=PackageVersion::$(cat version.json | jq -r .NuGetVersionV2)"
    - name: Run Build
      run: dotnet build -c Release
    - name: Run Tests
      run: >
        dotnet
        test
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=OpenCover
        /p:Exclude="+[Oxide*]*%2c-[Oxide.Tests]*"
    - name: Upload Coverage
      run: |
        export DOTNET_ROOT=/opt/hostedtoolcache/dncs/2.2.204/x64
        ~/.dotnet/tools/codecov -f "src/Oxide.Tests/coverage.opencover.xml" -t ${{ secrets.CODECOV_TOKEN }}
    - name: Pack NuGet
      run: >
        dotnet
        pack
        --include-symbols
        --no-build
        -c Release
        -o ./artifacts
        /p:SymbolPackageFormat=snupkg
        /p:Version=$PackageVersion
        /v:minimal
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Packages
        path: artifacts
    - name: Push All Builds To CI Feed
      run: >
        dotnet
        nuget
        push
        --source "github"
        ./artifacts/*.nupkg
    - name: Push Master Builds To NuGet
      run: >
        dotnet
        nuget
        push
        --api-key ${{ secrets.NUGET_API_KEY }}
        --Source https://api.nuget.org/v3/index.json
        ./artifacts/*.nupkg
      if: endsWith(github.ref, 'master')
